version: '3'

services:

  cc_backend:
    build: .
    image: cc_backend
    environment:
      - ENV_KEY=${ENV_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - .:/backend
    command: ["sh","-c", "echo ${ENV_KEY} \
                && python manage.py makemigrations \
                && python manage.py migrate \
                && python manage.py runserver 0.0.0.0:8000"]   
    ports:
      - "8000:8000"